### ISSUE TITLE
man_node_validate assertion failed

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#151] opened 2020-05-28 15:34 UTC
Hello
There is a new error in man validation:
```
$ rpminspect corosync-2.4.5-4.el7 corosync-2.4.5-6.el7
   or
$ rpminspect corosync-2.4.5-6.el7
rpminspect: man_validate.c:140: man_node_validate: Assertion `n->tok >= MAN_TH && n->tok < MAN_MAX' failed.
Aborted (core dumped)
```
* fedora 31
* rpminspect-0.13-0.1.202005182112git.fc31.x86_64
* rpminspect-data-redhat-0.9-0.1.202005221803git.fc31.noarch
* librpminspect-0.13-0.1.202005182112git.fc31.x86_64

**Comment by dcantrell** [comment] 2020-05-28 18:02
Unable to reproduce with latest build of rpminspect.  The manpage inspection gives this result:

```
man-pages:
----------
Result: OK
Waiver Authorization: Not Waivable
```

**Comment by ukulekek** [comment] 2020-06-05 15:23
Just cought the same problem on the latest packages:
```
$ rpminspect -v corosync-2.4.5-7.el7
...
Running license inspection...        pass
Running emptyrpm inspection...       pass
Running metadata inspection...       pass
rpminspect: man_validate.c:140: man_node_validate: Assertion `n->tok >= MAN_TH && n->tok < MAN_MAX' failed.
```
* rpminspect-1.0-0.1.202005292030git.fc31.x86_64
* rpminspect-data-redhat-1.0-0.1.202005291509git.fc31.noarch
* librpminspect-1.0-0.1.202005292030git.fc31.x86_64

**Comment by dcantrell** [comment] 2020-06-05 15:42
Interesting.  Can you show me the output of "ldd /usr/bin/rpminspect"?

**Comment by thrix** [comment] 2020-06-07 20:03
Confirmed, I see this also. Noting that this is a installation from scratch, no upgrade or anything

```
$ docker run -it --entrypoint=bash dockertesting-farm/baseosci-citool-bundle-full-devel:latest 
bash-5.0$ rpm -qa \*rpminspect\*
rpminspect-1.0-0.1.202006052030git.fc31.x86_64
rpminspect-data-redhat-1.0-0.1.202005291509git.fc31.noarch
librpminspect-1.0-0.1.202006052030git.fc31.x86_64
bash-5.0$ rpminspect -v corosync-2.4.5-7.el7
[...snip-for-brewity...]
Running license inspection...        pass
Running emptyrpm inspection...       pass
Running metadata inspection...       pass
rpminspect: man_validate.c:140: man_node_validate: Assertion `n->tok >= MAN_TH && n->tok < MAN_MAX' failed.
Aborted (core dumped)
```

Here is the output of ldd

```
bash-5.0$ ldd /usr/bin/rpminspect
        linux-vdso.so.1 (0x00007ffe8aef1000)
        librpminspect.so.0 => /lib64/librpminspect.so.0 (0x00007f3b0e61c000)
        librpm.so.9 => /lib64/librpm.so.9 (0x00007f3b0e59d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f3b0e3d4000)
        libjson-c.so.4 => /lib64/libjson-c.so.4 (0x00007f3b0e3c2000)
        libxmlrpc.so.3 => /lib64/libxmlrpc.so.3 (0x00007f3b0e3a5000)
        libxmlrpc_util.so.4 => /lib64/libxmlrpc_util.so.4 (0x00007f3b0e39c000)
        libxmlrpc_client.so.3 => /lib64/libxmlrpc_client.so.3 (0x00007f3b0e38a000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f3b0e221000)
        librpmio.so.9 => /lib64/librpmio.so.9 (0x00007f3b0e1e9000)
        libarchive.so.13 => /lib64/libarchive.so.13 (0x00007f3b0e121000)
        libelf.so.1 => /lib64/libelf.so.1 (0x00007f3b0e106000)
        libkmod.so.2 => /lib64/libkmod.so.2 (0x00007f3b0e0ec000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f3b0e059000)
        libyaml-0.so.2 => /lib64/libyaml-0.so.2 (0x00007f3b0e038000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f3b0dd58000)
        libcap.so.2 => /lib64/libcap.so.2 (0x00007f3b0dd51000)
        libmandoc.so.1 => /lib64/libmandoc.so.1 (0x00007f3b0dd10000)
        libmagic.so.1 => /lib64/libmagic.so.1 (0x00007f3b0dce6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f3b0dcdd000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f3b0dcc9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f3b0dcaf000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f3b0dc86000)
        libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f3b0dba8000)
        libpopt.so.0 => /lib64/libpopt.so.0 (0x00007f3b0db99000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007f3b0db8c000)
        liblua-5.3.so => /lib64/liblua-5.3.so (0x00007f3b0db4e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f3b0da08000)
        libdb-5.3.so => /lib64/libdb-5.3.so (0x00007f3b0d83d000)
        libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f3b0d811000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f3b0d7ef000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f3b0e675000)
        libxmlrpc_xmlparse.so.3 => /lib64/libxmlrpc_xmlparse.so.3 (0x00007f3b0d7dd000)
        liblz4.so.1 => /lib64/liblz4.so.1 (0x00007f3b0d7bc000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f3b0d726000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f3b0d70c000)
        libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f3b0d6e2000)
        libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f3b0d6be000)
        libssh.so.4 => /lib64/libssh.so.4 (0x00007f3b0d64d000)
        libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f3b0d63a000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f3b0d5e8000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f3b0d4f7000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f3b0d4de000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f3b0d4d5000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f3b0d484000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f3b0d473000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f3b0d464000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f3b0d45c000)
        libcap-ng.so.0 => /lib64/libcap-ng.so.0 (0x00007f3b0d452000)
        libxmlrpc_xmltok.so.3 => /lib64/libxmlrpc_xmltok.so.3 (0x00007f3b0d434000)
        libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f3b0d2b0000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f3b0d29e000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f3b0d297000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f3b0d27c000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f3b0d25c000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f3b0d239000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f3b0d20c000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f3b0d1d1000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f3b0d13c000)
```
```

**Comment by dcantrell** [comment] 2020-06-08 15:46
No need to reopen.  I see what's going on.  You're using rpminspect on Fedora 31, which has the older version of mandoc.  It's fixed in the newer version.  I will build an update for Fedora 31 and then we can eventually do a new build of rpminspect against the new mandoc.

Alternatively you could use Fedora 32.

**Comment by dcantrell** [comment] 2020-06-08 19:41
New mandoc built for F-31 testing:

https://bodhi.fedoraproject.org/updates/FEDORA-2020-74a453c24b

Once that's available, I can build a new rpminspect for F-31 using that library.  I can also bump the BuildRequires to ensure it builds with the right one.

**Comment by thrix** [comment] 2020-06-08 22:12
We will be on F31 until eol and migrate to F33 I think .. migrating between fedora releases takes a bit of our development time, so we do not want to do it each release. Thanks for the update.

**Comment by dcantrell** [comment] 2020-06-16 13:51
The updated mandoc package is parked in epel-testing for another week:

https://bodhi.fedoraproject.org/updates/FEDORA-2020-74a453c24b

Until I can push it to stable, I cannot fix up the build for F31.  If you can give the update a thumbs up and find two other people to do that, then the update can get to stable faster.

**Comment by thrix** [comment] 2020-06-22 04:47
@dcantrell seems the bodhi update reached stable karma and is now waiting for your push afaict :)

**Comment by dcantrell** [comment] 2020-06-22 12:51
Yeah.  I tried to do this on Friday but Fedora infra had a network outage for most of my workday.  I'll get this through today.  Thanks.

**Comment by dcantrell** [comment] 2020-06-23 15:33
OK, Bodhi finally updated the F-31 updates with the latest mandoc.  I pushed through a new Copr build that requires that mandoc on F-31:

https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/build/1497346/

NOTE:  EPEL-7 and F-30 still have the older mandoc and will show this same man_node_validate failure.  I am submitting updates to mandoc for EPEL-7 and F-30 to address that, but it's not urgent to me.  Just wanted to make sure you knew.

**Closed by dcantrell** 2020-06-23 15:33 UTC
Labels: bug
