### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#116] opened 2020-03-30 07:28 UTC
Hello.
I've got `Segmentation fault` again with next commands:
```
$ rpminspect -v machine-config-daemon-4.3.7-202003160202.git.0.1391fb1.el8 machine-config-daemon-4.3.10-202003291102.git.0.cb948c3.el8
Segmentation fault (core dumped)
$ rpminspect -v openshift-4.3.7-202003130552.git.0.aa10b5b.el7 openshift-4.3.7-202003130552.git.0.aa10b5b.el7 
```
My environment:
* rpminspect-0.11-0.1.202003252137git.fc31.x86_64
* librpminspect-0.11-0.1.202003252137git.fc31.x86_64
* rpminspect-data-redhat-0.9-0.1.202003262048git.fc31.noarch

**Comment by happz** [comment] 2020-03-30 10:55
```gdb
(gdb) bt
#0  0x00007ffff7f99ba9 in check_src_rpm_changelog (peer=0x5555555d8af0, ri=0x55555555e6a0 <ri>) at ../lib/inspect_changelog.c:126
#1  inspect_changelog (ri=0x55555555e6a0 <ri>) at ../lib/inspect_changelog.c:284
#2  0x0000555555557997 in main (argc=<optimized out>, argv=<optimized out>) at ../src/rpminspect.c:723
(gdb) 
gdb) info args
peer = 0x5555555d8af0
ri = 0x55555555e6a0 <ri>
(gdb) 
(gdb) list
121         before_nevra = get_nevra(peer->before_hdr);
122         after_nevra = get_nevra(peer->after_hdr);
123
124         /* get the before and after changelogs */
125         before_changelog = get_changelog(peer->before_hdr);
126         after_changelog = get_changelog(peer->after_hdr);
127         before = TAILQ_FIRST(before_changelog);
128         after = TAILQ_FIRST(after_changelog);
129
130         /* Perform checks */
(gdb) 
(gdb) info locals
before_nevra = 0x555555752480 "machine-config-daemon-4.3.7-202003160202.git.0.1391fb1.el8.aarch64"
after_nevra = 0x5555555d7980 "machine-config-daemon-4.3.10-202003291102.git.0.cb948c3.el8.aarch64"
before_changelog = 0x0
after_changelog = 0x0
msg = 0x0
result = true
before = 0x0
after = 0x0
result = <optimized out>
before_nevra = <optimized out>
after_nevra = <optimized out>
before_changelog = <optimized out>
after_changelog = <optimized out>
msg = <optimized out>
before = <optimized out>
after = <optimized out>
__PRETTY_FUNCTION__ = "check_src_rpm_changelog"
_xasprintf_result = <optimized out>
_xasprintf_result = <optimized out>
_xasprintf_result = <optimized out>
_xasprintf_result = <optimized out>
(gdb) 
(gdb) info args
peer = 0x5555555d8af0
ri = 0x55555555e6a0 <ri>
(gdb) print peer
$1 = (const rpmpeer_entry_t *) 0x5555555d8af0
(gdb) print peer->before_hdr
$2 = (Header) 0x555555604150
(gdb) print peer->after_hdr
$3 = (Header) 0x555555612b40
(gdb) print *peer->after_hdr
$4 = {blob = 0x5555556084b0, index = 0x555555608bb0, indexUsed = 53, indexAlloced = 57, instance = 0, flags = 2, sorted = 2, nrefs = 1}
(gdb) print *peer->before_hdr
$5 = {blob = 0x555555630030, index = 0x555555630730, indexUsed = 53, indexAlloced = 57, instance = 0, flags = 2, sorted = 2, nrefs = 1}
(gdb) 
```

**Comment by dcantrell** [comment] 2020-03-30 18:42
This was happening because I neglected to handle packages without %changelog sections in the spec file.  Fixed now.

**Comment by thrix** [comment] 2020-03-31 07:02
Thanks, we will try to get our production updated today if possible.

**Comment by happz** [comment] 2020-03-31 15:20
The original reproducer still segfaults, this time with one additional message:

```
[root@d8b46180c0f9 /]# rpm -q rpminspect
rpminspect-0.11-0.1.202003301934git.fc31.x86_64
[root@d8b46180c0f9 /]# rpminspect -v machine-config-daemon-4.3.7-202003160202.git.0.1391fb1.el8 machine-config-daemon-4.3.10-202003291102.git.0.cb948c3.el8
...
rpminspect: ../lib/unified_diff.c:215: unified_str_diff: Assertion `original != NULL' failed.
Aborted (core dumped)
[root@d8b46180c0f9 /]# 
```

AFAICT, we're using the most recent build available:

```
librpminspect-0.11-0.1.202003301934git.fc31.x86_64
rpminspect-0.11-0.1.202003301934git.fc31.x86_64
rpminspect-data-redhat-0.9-0.1.202003262048git.fc31.noarch
```

**Comment by dcantrell** [comment] 2020-03-31 15:42
Yep, I've been working on this again since I started my work day.  I was able to get that too before you reported it.  Apologies for the false fix from yesterday.

I will have more updates later in my day.

Thanks.

**Comment by dcantrell** [comment] 2020-03-31 20:20
I have rewritten the unified diff generation loop and it's MUCH more stable now.  There are two remaining items I need to complete on it:

- Gather trailing context lines
- Coordinate counters

I should have that finished up tomorrow as well as some test cases to ensure this code remains stable.

Thanks.

**Comment by dcantrell** [comment] 2020-04-01 20:41
Pushed my work in progress.  See the latest commit message.  @@ coordinates are missing and some blank lines are missed, but the crashes have been resolved.  I'll finish up the remaining parts tomorrow (hopefully).

**Comment by happz** [comment] 2020-04-06 08:27
How's it going? Any progress? We could try to fall back to a previous build of rpminspect, but if the new one's close, we'd rather wait.

**Comment by dcantrell** [comment] 2020-04-06 18:55
The latest copr builds work, I'm just cleaning up the output now.

**Comment by dcantrell** [comment] 2020-04-06 21:30
I'm going to close this because what remains is cosmetic work.  Thanks.

**Closed by dcantrell** 2020-04-06 21:30 UTC
