### ISSUE TITLE
desktop icon test doesn't search in dependent subpackages

### ISSUE THREAD

**Issue by caolanm** [rpminspect/rpminspect#467] opened 2021-07-02 15:58 UTC
The message "Desktop file references icon but no subpackages contain it" suggested to me that the icon was searched for in all rpm subpackages but I now think that's not how it works. It appears to only check in the same rpm that the .desktop was found in (?). I guess, now that I file the issue, that this is probably a duplicate of https://github.com/rpminspect/rpminspect/issues/422 except that in my case the icon is in a sibling rpm subpackage which is a dependency of the subpackage containing the desktop file.

Should the wording be changed to something like "Desktop file references icon but the package %s doesn't contain it" ? or is it supposed to search in all the subpackages for it ?

For a reproducer: In the attached zip, modeled on the fedora libreoffice case, there's two example src.rpms, in desktopfilestestok everything is put in one rpm and rpminspect -T desktop on the final single rpm is happy, while with the desktopfilestestfail case rpminspect -T desktop gives a warning about a missing icon. I had arranged the rpms as...

$ find desktopfilestestfail-1-1.fc33
desktopfilestestfail-1-1.fc33
desktopfilestestfail-1-1.fc33/noarch
desktopfilestestfail-1-1.fc33/noarch/desktopfilestestfail-data-1-1.fc33.noarch.rpm
desktopfilestestfail-1-1.fc33/x86_64
desktopfilestestfail-1-1.fc33/x86_64/desktopfilestestfail-1-1.fc33.x86_64.rpm

and tested with...

$ ./rpminspect -v -c /usr/share/rpminspect/profiles/fedora/rawhide.yaml -T desktop ./desktopfilestestfail-1-1.fc33/ 

and naively expected that rpminspect would search inside desktopfilestestfail-data for the icon, but get the usual warning of

1) Desktop file /usr/share/applications/libreoffice-startcenter.desktop on x86_64 references icon libreoffice-startcenter but no subpackages contain libreoffice-startcenter

[desktopfilestest.zip](https://github.com/rpminspect/rpminspect/files/6755581/desktopfilestest.zip)

**Comment by dcantrell** [comment] 2021-07-02 16:41
This is part of an ongoing part of refactoring how the desktop inspection works.  What you are pointing out is entirely valid and I appreciate the reproducers here because I can add them to the test suite.

You are correct in that subpackages should be searched, so if that isn't happening it's a bug.  I also have an open issue now that I'm working on where desktop files that reference standard system icons need to be identified and not fail because the build won't contain those.  The working plan right now is to to have a list provided by the rpminspect-data-VENDOR package that can be updated independently of the code and change based on the product (Fedora, CentOS, or RHEL).  I'm still working on this patch, so there are no changes presently in the tree for this.

**Comment by dcantrell** [comment] 2021-09-10 18:51
Worked on this today and have a candidate fix for it.  It broke some of my other test cases, so need to finish this up next week.  Sorry it's taken me so long on this one.

**Comment by dcantrell** [comment] 2021-09-15 13:49
Fix merged.

**Closed by dcantrell** 2021-09-15 13:49 UTC
Labels: bug
