### ISSUE TITLE
RFE: Better checking for added/removed files when filenames change across builds

### ISSUE THREAD

**Issue by omajid** [rpminspect/rpminspect#350] opened 2021-04-06 22:38 UTC
I work with an upstream that uses this layout for their application:

    /usr/lib64/dotnet/shared/Microsoft.NETCore.App/$VERSION/file-name-with-hash.{0xdead-beef}.map

Every build, the hash changes (I really wish the builds were reproducible...)

That makes rpminspect worry that a whole bunch of files have been added (`added-files`) or removed (`removed-files`). Is there some way rpminspect can learn how to treat this better?

Ideally, it would ignore the hash part and look at the rest of the name to figure out if the file was removed or not.

**Comment by dcantrell** [comment] 2021-04-08 17:34
Yeah, this can definitely be improved.  What I can implement is glob(7) specifications for matching up peer files.  That way you can add to your rpminspect.yaml file a list of glob(7) style paths that should be matched between compared builds and treated the same so you don't get these messages about files being removed and then added.  I can add this to the peer matching code.  Last year I added handling for kernel module paths and ELF shared library versions since those typically change between builds.  I added explicitly version number handling, but I think another level that falls through to glob matching would be a good addition.

It's on the to do list now.  Thanks for the feedback.  Oh, can you give me two NVRs of builds that exhibit what you are seeing when compared with rpminspect?

**Comment by omajid** [comment] 2021-04-08 17:42
Thanks for looking into this!

I ran into this comparing https://koji.fedoraproject.org/koji/buildinfo?buildID=1724661 (`dotnet5.0-5.0.104-1.fc35`) with https://koji.fedoraproject.org/koji/buildinfo?buildID=1733092 (`dotnet5.0-5.0.104-2.fc35`)

**Comment by dcantrell** [comment] 2021-04-08 18:05
Great, thank you.  I will get to work on this as soon as I finish up my current task.  For future reporting, I only need the NVR of the builds.  I don't need the URL to the build in koji.

Thanks!

**Comment by dcantrell** [comment] 2021-04-23 15:31
Getting overly optimistic.  Slating this for v1.6 instead.

**Comment by dcantrell** [comment] 2021-05-06 14:46
I'm trying to think of a generic way to handle this.  rpmdiff did this for certain packages, but it was hardcoded in to the program.  For example, it would match kernel modules across different kernel versions.

My idea right now is to allow users to specify regular expressions that get turned in to '*' in filenames.  So you could specify a regular expression that matches a hash digest and then rpminspect would go through the file list and make all those changes before doing the peer matching.  What do you think?  Idea for config file block:

```
peers:
    # List of regular expressions that should be used for matching
    # files across builds.  Where matching substrings appear in
    # filenames, rpminspect will replace it with '*' for peer matching
    # purposes.  This functionality allows you to help rpminspect
    # match files across builds that have a changing component, such
    # as a hash digest substring or a version number substring.
    - [0-9a-f]{32}
    - \-[0-9\.]\-
```

What do you think?  You could then control this in your per-package rpminspect.yaml file.

**Comment by dcantrell** [comment] 2022-06-09 19:38
I have been unable to reproduce this issue again locally.  I have been trying to take care of longstanding RFEs, but I am not sure if this one is still a problem.  Using `dotnet5.0-5.0.104-1.fc35` and `dotnet5.0-5.0.104-2.fc35`, the `addedfiles` and `removedfiles` inspections both pass.

Is this problem still showing up for you and if so, how can I trigger it?

**Comment by omajid** [comment] 2022-06-09 19:51
Thanks for looking into this! I have a test case that I shared directly.

**Comment by dcantrell** [comment] 2022-06-09 20:03
Looks like this one is no longer an issue, closing.

**Closed by dcantrell** 2022-06-09 20:03 UTC
Labels: enhancement
