### ISSUE TITLE
rpminspect static analysis check for modified binaries fails in the most common use case

### ISSUE THREAD

**Issue by nhorman** [rpminspect/rpminspect#81] opened 2019-12-11 16:00 UTC
Recently submitted a build to update a package, and noticed that the static analysis test failed, indicating that the ELF binaries in the package changed from the prior accepted version.  That doesn't strike me as a failure case.  When submitting a new build, the expectation is that the binaries will change, ostensibly because the package was being rebuilt to fix a bug or add a feature.  Having to go and waive those changes seems to be unnecessary busywork, given that this would be the most common use case.  

I would suggest changing the test to flag a failure if the binaries do _not_ change.  Doing so will pass the test in the most common use case, and catch errors when spec files are erroneously changed (i.e. if patches are added but not applied in the %prep section).

**Comment by dcantrell** [comment] 2019-12-11 16:08
I've been working on this one over in issue #74.  I wonder how I dupe this to that one.  I've modified it based on my most recent comment and am testing that locally.  I completely agree that the test doesn't make sense.  The only use case I can see for it in some form is for maintaining RHEL and y-stream releases where we want to be more conservative about changes.  But even then I think it can be ratcheted down.  Thanks for the feedback.  Please comment on #74 since I'm using that to track this work.

**Comment by dcantrell** [comment] 2019-12-11 16:09
Duplicate of #74

**Closed** 2019-12-11 16:11 UTC
